steps:
  # Step 0: Clear existing image
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'auth'
      - 'configure-docker'
      - '--quiet'
  
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'container'
      - 'images'
      - 'list-tags'
      - 'gcr.io/$PROJECT_ID/realTimeMessagingApp'
      - '--filter=tags=latest'
      - '--format=value(digest)'
    id: check-existing-image
  
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'container'
      - 'images'
      - 'delete'
      - 'gcr.io/$PROJECT_ID/realTimeMessagingApp@$(cat $ID_FILE)'
      - '--quiet'
    waitFor:
      - check-existing-image

  # Step 1: Clone the repository
  - name: 'gcr.io/cloud-builders/git'
    args: ['clone', 'https://github.com/muhammadhumzadev/realtime_messaging_app.git', 'repo']
    dir: 'repo'

  # Step 2: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/realTimeMessagingApp', '.']
  
  # Step 3: Push the Docker image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/realTimeMessagingApp']
  
  # Step 4: Deploy the Docker image to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'realTimeMessagingAppCloud'
      - '--image'
      - 'gcr.io/$PROJECT_ID/realTimeMessagingApp'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
