steps:
  # Step 1: Clone the repository
  - name: 'gcr.io/cloud-builders/git'
    args: ['clone', 'https://github.com/muhammadhumzadev/realtime_messaging_app.git', '.']
  
  # Step 2: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/realTimeMessagingApp', '.']
  
  # Step 3: Push the Docker image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/realTimeMessagingApp']
  
  # Step 4: Deploy the Docker image to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'realTimeMessagingAppCloud'
      - '--image'
      - 'gcr.io/$PROJECT_ID/realTimeMessagingApp'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
